# FLASK
DEBUG = True

# DB
MONGO_HOST = 'localhost'
MONGO_PORT = 27017
MONGO_DBNAME = 'eve_blog'

# DOMAIN
DOMAIN = {}

# URL
URL_PREFIX = 'api'
API_VERSION = 'v1'

# METHODS
RESOURCE_METHODS = ['GET', 'POST', 'DELETE']
ITEM_METHODS = ['GET', 'PATCH', 'PUT', 'DELETE']
